export default {
  INTERNAL: 'E_INTERNAL_SERVER',
  VALIDATION: 'E_VALIDATION',
  INVALID_PARAMS: 'E_INVALID_PARAMS',
  UNAUTHORIZED: 'E_UNAUTHORIZED',
  FORBIDDEN: 'E_FORBIDDEN',
  NOT_FOUND: 'E_NOT_FOUND',
  ROUTE_NOT_FOUND: 'E_ROUTE_NOT_FOUND',
  BAD_REQUEST: 'E_BAD_REQUEST',
  INVALID_EMAIL_PASSWORD: 'E_INVALID_EMAIL_PASSWORD',
  CONFLICT: 'E_CONFLICT',
}
