type UserJWT {
  _id: String!
  email: String!
  token: String
}

type User {
  first_name: String
  last_name: String
  avatar_url: String
}

extend type Mutation {
    signIn(email: String!, password: String!): UserJWT
    emailSignUp(email: String!, password: String!): UserJWT
    facebookSignUp(token: String!): UserJWT
    googleSignUp(token: String!): UserJWT
}
